### ISSUE TITLE
Cannot read properties of undefined (reading 'nestable')

### ISSUE THREAD

**Issue by abrardev99** [solutionforest/filament-tree#37]
Hi, I'm facing the following issue: 

Alpine Expression Error: Cannot read properties of undefined (reading 'nestable')
```
Expression: "function () {

let nestedTree = $('#filament_tree_container_BxCAKyCkwLPukL2rHBKg').nestable
.
.
.
```

To be exact, it's happening in components/tree/index.php file. Looks like its not able to find the JQuery here. `$('#{{ $containerKey }}')` returns undefined while `document.getElementById('{{ $containerKey }}')` returns object.

**Comment by abrardev99** [comment]
The temporary solution we adopted is loading Jquery and package js at the end of file. For example, we created the view: 
```
<script src="https://code.jquery.com/jquery-3.6.1.slim.min.js"
        integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA="
        crossorigin="anonymous"></script>
<script src="{{asset('js/solution-forest/filament-tree/filament-tree-min.js')}}"></script>

```

And loaded it at the end of body using Filament hook. 

```
->renderHook(
    'panels::body.end',
    fn (): View => view('filament/resources/custom-body-end-js-cmspanel'),
)
```

**Comment by abrardev99** [comment]
I attempted a PR that registers JS assets at the body end. https://github.com/solutionforest/filament-tree/pull/38

**Comment by RemiHin** [comment]
Running in to this issue aswell

**Comment by curder** [comment]
Same issue, Sometimes due to unstable network, will encounter the problem that jquery-3.6.0.min.js cannot be loaded.

Below is my solution:

1. Add new middleware named `ReplaceAssets` and replace `<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>` string.
2. Register the new middleware.
3. Download `jquery-3.6.0.min.js` and saved to `public/js/solution-forest/filament-tree/jquery.min.js`.
4. Loaded it at the start of body using Filament hook.

Below is the demo code:

1. Add new middleware

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ReplaceAssets
{
    /**
     * Handle an incoming request.
     *
     * @param  Closure(Request): (Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        $search = '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
        $replace = '';

        $response->setContent(Str::replace($search, $replace, $response->getContent()));

        return $response;
    }
}
```

2. Register middleware

```php
<?php

namespace App\Providers\Filament;

use App\Http\Middleware\ReplaceAssets;

class AdminPanelServiceProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            // ...
            ->middleware([
                // ...
                DispatchServingFilamentEvent::class,
                ReplaceAssets::class, // Add this line
            ]);
    }
}
```

3. Download `jquery-3.6.0.min.js` to `public/js/solution-forest/filament-tree/jquery.min.js`
4. Loaded it at the start of body using Filament hook

```php
<?php

namespace App\Providers\Filament;

use function asset;

class AdminPanelServiceProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            // ...
            ->renderHook(
                'panels::body.start',
                fn (): string => sprintf("<script src='%s'></script>", asset('js/solution-forest/filament-tree/jquery.min.js')),
            );
    }
}
```

**Comment by 199ocero** [comment]
Hi @curder  and @abrardev99 this solves me issue. Now another problem shows when using spa mode in filament. The problem is when I tried to load the page for tree plugin it works but when I try to navigate for another page and go back to tree page it does not load the js and it results to showin the `Uncaught (in promise) TypeError: $(...).nestable is not a function`. Would you mind sharing a solution for this? I can't really make it work in my end.

**Comment by iotron** [comment]
Hello, any update on this issue?

**Comment by cklei-carly** [comment]
See [#51 ](https://github.com/solutionforest/filament-tree/issues/51#issuecomment-2268727832)
